<a href="https://colab.research.google.com/github/MichelMurwanashyaka/Michel/blob/master/hove_kouevi_Quiz3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%%javascript
MathJax.Hub.Config({
    TeX: { equationNumbers: { autoNumber: "AMS" } }
});

<IPython.core.display.Javascript object>

In [ ]:
import numpy as np


# $$\text{Exercise 1}$$
1. Let us consider the array $M$ defined below

In [ ]:
import numpy as np
M = np.array([[ 80842, 333008, 202553, 140037,  81969,  63857,  42105, 261540],
       [481981, 176739, 489984, 326386, 110795, 394863,  25024,  38317],
       [ 49982, 408830, 485118,  16119, 407675, 231729, 265455, 109413],
       [103399, 174677, 343356, 301717, 224120, 401101, 140473, 254634],
       [112262,  25063, 108262, 375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041, 188411, 335140, 141681],
       [ 59641, 211420, 287650,   8973, 477425, 382803, 465168,   3975],
       [ 32213, 160603, 275485, 388234, 246225,  56174, 244097,   9350],
       [496966, 225516, 273338,  73335, 283013, 212813,  38175, 282399],
       [318413, 337639, 379802, 198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007,  52547, 180346, 178760],
       [305186, 262153,  11835, 449971, 494184, 472031, 353049, 476442],
       [ 35455, 191553, 384154,  29917, 187599,  68912, 428968,  69638],
       [ 20140, 220691, 163112,  47862, 474879,  15713, 279173, 161443],
       [ 76851, 450401, 193338, 189948, 211826, 384657,  17636, 189954],
       [182580, 403458,  63004,  87202,  17143, 308769, 316192, 408259],
       [379223, 322891, 302814, 309594,  13650,  68095, 327748,  27138],
       [ 33346, 202960, 221234,  61986,  96524, 230606, 266487, 299766],
       [ 46264,  33510, 434647,  26750, 412754, 346058, 263454, 270444],
       [182770, 486269, 402948, 105055, 463911, 378799, 329053,  16793],
       [379586, 293162, 121602, 144605, 105553,  71148,  40126, 183534],
       [493338,   5241, 498084, 189451, 219466,  12869, 482845,  16529],
       [145955, 461866, 427009,  70841, 318111, 199631,  99330, 407887],
       [133826, 214053, 295543, 339707, 199545, 194494, 304822, 337793],
       [395524, 206326, 308488, 297633, 472409, 487606, 422244, 443487],
       [464749,  75275, 299486, 248984,  76076, 197544,  75103, 394086],
       [404365,  67309, 267556,  96483, 166099, 203867,  57120, 211249],
       [ 86992, 286426, 130451, 419955, 109839, 332663, 101095,  50820],
       [108699, 436141, 333670,  45890, 425798,   6967, 155851, 360687],
       [252907, 121138,  81509, 367876, 471831, 226950, 349068, 197092]])
M.shape


(30, 8)

1. What is the average value of the second and fourth columns?

In [ ]:
M[:,1:4:2]

array([[333008, 140037],
       [176739, 326386],
       [408830,  16119],
       [174677, 301717],
       [ 25063, 375059],
       [129585, 313094],
       [211420,   8973],
       [160603, 388234],
       [225516,  73335],
       [337639, 198049],
       [425024, 117968],
       [262153, 449971],
       [191553,  29917],
       [220691,  47862],
       [450401, 189948],
       [403458,  87202],
       [322891, 309594],
       [202960,  61986],
       [ 33510,  26750],
       [486269, 105055],
       [293162, 144605],
       [  5241, 189451],
       [461866,  70841],
       [214053, 339707],
       [206326, 297633],
       [ 75275, 248984],
       [ 67309,  96483],
       [286426, 419955],
       [436141,  45890],
       [121138, 367876]])

In [ ]:
np.average(M[:,1:4:2])

218960.13333333333

2. What is the average value of the last 5 rows of the second and fourth columns?

In [ ]:
M[:5,1:4:2]

array([[333008, 140037],
       [176739, 326386],
       [408830,  16119],
       [174677, 301717],
       [ 25063, 375059]])

In [ ]:
np.average(M[:5,1:4:2])

227763.5

3. Update $M$ by Replacing all its even integers by 0.

In [ ]:
for i in range(0,30):
  for j in range(0,8):
    if M[i,j]%2==0:
      M[i,j]=0
M

array([[     0,      0, 202553, 140037,  81969,  63857,  42105,      0],
       [481981, 176739,      0,      0, 110795, 394863,      0,  38317],
       [     0,      0,      0,  16119, 407675, 231729, 265455, 109413],
       [103399, 174677,      0, 301717,      0, 401101, 140473,      0],
       [     0,  25063,      0, 375059, 406983, 208947, 115641, 296685],
       [444899, 129585,      0,      0, 425041, 188411,      0, 141681],
       [ 59641,      0,      0,   8973, 477425, 382803,      0,   3975],
       [ 32213, 160603, 275485,      0, 246225,      0, 244097,      0],
       [     0,      0,      0,  73335, 283013, 212813,  38175, 282399],
       [318413, 337639,      0, 198049, 101115, 419547, 260219, 325793],
       [148593,      0,      0,      0, 107007,  52547,      0,      0],
       [     0, 262153,  11835, 449971,      0, 472031, 353049,      0],
       [ 35455, 191553,      0,  29917, 187599,      0,      0,      0],
       [     0, 220691,      0,      0, 474879,  15

# $$\text{Exercise 2}$$

Let $\{ x_k\}$ be a partition of $[a,b]$ such that $a=x_0<x_1<\cdots<x_{N-1}<x_N=b$ and $H$ be the length of the $k$-th subinterval ($H = x_k - x_{k-1}$),
then we have 
$$\int_a^bf(x)dx \approx \sum_{k=1}^N \frac{f(x_{k-1})+f(x_k)}{2}H = A$$


Write a function named <b>Trap</b> that takes $a,b,N, f$ as inputs and return A

In [ ]:
def trapz(f,a,b,N=50):

    x = np.linspace(a,b,N+1) # N+1 points make N subintervals
    y = f(x)
    y_right = y[1:] # right endpoints
    y_left = y[:-1] # left endpoints
    dx = (b - a)/N
    A = (dx/2) * np.sum(y_right + y_left)
    return A
trapz(lambda x: x**2+2*x, 0,2)

6.667199999999999

# $$\text{Exercise 3}$$

Let us consider the function $f$ defined on the set of integer as follows 

\begin{equation}
f(n) =
  \begin{cases}
    n/2       & \quad \text{if } n \text{ is even}\\
    -(n)/3 +1  & \quad \text{if } n \text{ is odd and divisible by 3}\\
    (n+1)/2 +1 & \quad \text{else}
  \end{cases}
\end{equation}

Write a python function named <b> ComptFunc </b> that takes two intergers $a$ and $b$ , $a<b$ and return  an array $flist$ of all  $f(n), n \in nlist$ where $nlist$ is the list of all the integers in the interval $[a,b]$.

In [ ]:
#a=input('Enter an integer value of a:')
#b=input('Enter an integer value of b:')
def ComptFunc(a,b):
  flist=[]
  if a > b:
    return []
  else:

    nlist = np.linspace(a,b,a+b,dtype=int)
    for n in nlist:
      if n%2 == 0:
        flist.append(n/2)
      if n%2==1 and n%3==0:
        flist.append(1-n/3)
      else:
        flist.append(1+(n+1)/2)
    return flist


ComptFunc(3,5)

[0.0, 0.0, 0.0, 0.0, 2.0, 3.5, 2.0, 3.5, 2.0, 3.5, 4.0]

# $$\text{Exercise 4}$$

Write a python code to create the following numpy arrays
$$
A = \begin{pmatrix}
1 & 4 & 6 \\ 
0 & -3 & 2 \\ 
-2 & -2 & -2	
\end{pmatrix}, \quad
B = \begin{pmatrix}
2 & -1 & 0 \\ 
2 & -1 & 0 \\ 
2 & -3 & 1
\end{pmatrix},
$$
and compute $A-B$, $4A + B$, $trace(A)$, $B^t$ the transpose of $B$, the determinant of $A$, $AB$ and $BA^t$

<IPython.core.display.Javascript object>

# $$\text{Exercise 5}$$

Let us consider the sequence $U_n$ given by 
\begin{equation}\label{fib}
\left\lbrace 
\begin{array}{ll}
U_0 &= 1,\\
U_1 &= 2,\\
U_{n} &=-3U_{n-1} +U_{n-2}, \;\; \forall\; n=2,3,4\cdots
\end{array}\right. 
\end{equation}

Write a python function named  <b>SeqTerms</b> that takes as input an integer $n,\;\;n\geq 0$ and return an array of the first $n$ terms (i.e. $U_0, \cdots, U_{n-1}$) of the sequence \eqref{fib}.